name: Terraform Automation

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.11  # Specify the version of Terraform you want to use

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform changes
      run: terraform apply -auto-approve

    - name: Clean up
      run: terraform destroy -auto-approve
